language: bash
dist: bionic

git:
  depth: false

branches:
  only:
    - dev

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

addons:
  snaps:
   - name: snapcraft
     channel: stable
     confinement: classic
   - name: multipass
     channel: stable
     confinement: classic

script:
  - sudo snapcraft
  - sudo snapcraft clean
  - sudo snapcraft --target-arch arm64

after_failure:
  - sudo journalctl -u snapd

deploy:
  provider: snap
  snap: qv2ray_*.snap
  channel: edge
  skip_cleanup: true
  on:
    branch: dev